services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1nSid3C@se
    ports:
      - "5432:5432"
    volumes:
      - ./InsideCaseDB.sql:/docker-entrypoint-initdb.d/InsideCaseDB.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@insidecase.com
      PGADMIN_DEFAULT_PASSWORD: 1nSid3C@se1
    ports:
      - "8080:80"
