CREATE DATABASE insidecase;

\c insidecase;

CREATE TABLE "Order" (
    Id SERIAL PRIMARY KEY NOT NULL,
    Total_Amount INTEGER NOT NULL,
    Total_Price NUMERIC NOT NULL,
    Removed BOOLEAN NOT NULL DEFAULT FALSE,
    Closed BOOLEAN NOT NULL DEFAULT FALSE,
    Created_At TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "Product" (
    Id SERIAL PRIMARY KEY NOT NULL,
    Name_Product VARCHAR(100) NOT NULL,
    Price NUMERIC NOT NULL,
    Stock NUMERIC NULL,
    Removed BOOLEAN NOT NULL DEFAULT FALSE,
    Created_At TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "Product_Order" (
    Id SERIAL PRIMARY KEY NOT NULL,
    Order_Id INTEGER NOT NULL REFERENCES "Order"(Id),
    Product_Id INTEGER NOT NULL REFERENCES "Product"(Id),
    Amount INTEGER NOT NULL,
    Created_At TIMESTAMPTZ NOT NULL DEFAULT NOW()
);